package net.milosvasic.conferences.bosch.meet_the_kotlin_lecture

val logo = """MMWXKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXNWMM
MMKo::::::::::::::::::::::::::::::::::::::::::::cllllllllllllllllllllllllllllllllllllllllllllloxKWMM
MMKc;;,,,,,;,,,,,,,,,,,,,,,,,,,,,,,,,,,;;,;;;;:cccccccccccccccccccccccccccccccccccccccccccccld0NWMMM
MMKc;,,;;;;;;;;;;;;;;;;;;;;;;;;;;,;;;,;,,;;;:cccccccccccccccccccccccccccccccccccccccccccccld0NWMMMMM
MMKc;,,;;;;;;;;;;;;;;;;;;;;;;;;,,,;;;,;;;;::ccccccccccccccccccccccccccccccccccccccccccccld0NWMMMMMMM
MMKc;,,;;;;;;;;;;;;;;;;;;;;;;;;,,,;;,,;;;:ccccccccccccccccccccccccccccccccccccccccccccld0NWMMMMMMMMM
MMKc;,,;;;;;;;;;;;;;;;;;;;;;;;;;,,;;;;;:ccccccccccccccccccccccccccccccccccccccccccccld0NWMMMMMMMMMMM
MMKc;,,;;;;;;;;;;;;;;;;;;;;;;;;,,;;;;:ccccccccccccccccccccccccccccccccccccccccccccld0NWMMMMMMMMMMMMM
MMKc,,,;;;;;;;;;;;;,,;;;,;;;;;,,;;;:ccccccccccccccccccccccccccccccccccccccccccccld0NWMMMMMMMMMMMMMMM
MMKc,,,;;;;;;;;;;;;;;;;;,,,;;,;;;:ccccccccccccccccccccccccccccccccccccccccccccld0NWMMMMMMMMMMMMMMMMM
MMKc,,,;;;;;;;;;;;;;;;;;;;;,,;;:ccccccccccccccccccccccccccccccccccccccccccccld0NWMMMMMMMMMMMMMMMMMMM
MMKc,,,;;;;;;;;;;,,;;,;;;,,;;:ccccccccccccccccccccccccccccccccccccccccccccld0NWMMMMMMMMMMMMMMMMMMMMM
MMKc,,,;;;;;;;;;,,;;,,,,,;;:ccccccccccccccccccccccccccccccccccccccccccccldONWMMMMMMMMMMMMMMMMMMMMMMM
MMKc,,,;;;;;;;;;;;,,;;;,;::cccccccccccccccccccccccccccccccccccccccccccld0NWMMMMMMMMMMMMMMMMMMMMMMMMM
MMKc,,,;;;;;;;;;;;;;,;;;:cccccccccccccccccccccccccccccccccccccccccccld0NWMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMKc;,,;;,;;;;;;;;,,;;:cccccccccccccccccccccccccccccccccccccccccccld0NWMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMKc;,,;;;;;;,,;;,;;:cccccccccccccccccccccccccccccccccccccccccccldONWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMKc;,,;;;;,,;;,;;:cccccccccccccccccccccccccccccccccccccccccccldONWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMKc;,,;;,;;,,;;:cccccccccccccccccccccccccccccccccccccccccccld0NWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMKc;,,;,,;;;;:cccccccccccccccccccccccccccccccccccccccccccldONWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMKc,,,,;;;;:cccccccccccccccccccccccccccccccccccccccccccldONWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMKc;;,,;;:cccccccccccccccccccccccccccccccccccccccccccldOXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMKc;,;;:cccccccccccccccccccccccccccccccccccccccccccldONWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMKl;;::ccccccccccccccccccccccccccccccccccccccccclldONWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMKl;:ccccccccccccccccccccccccccccccccccccccccccclokNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMKoccccccccccccccccccccccccccccccccccccccccccc:;;;:o0NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MWKdccccccccccccccccccccccccccccccccccccccccc:;;,;;;;:o0NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMKdccccccccccccccccccccccccccccccccccccccc:;;,,,;;;;;;:o0NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMKdccccccccccccccccccccccccccccccccccccc:;;;;;,;;;;;,;;;:o0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MWKdccccccccccccccccccccccccccccccccccc:;;,;;,,;;;;;;;;;,;;:d0NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MWKdccccccccccccccccccccccccccccccccc:;;;;,,;;,,,;;;;;;;;,,;;:d0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMKdccccccccccccccccccccccccccccccc:;;,,;;;,,,;;;;;;;;;;;,,;;,;:d0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMKdccccccccccccccccccccccccccccc:;;;;,,;;;,;;;;;;;;;;;;;;;;;;;;;:d0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMKdccccccccccccccccccccccccccc:;;,;;,,;;;;;;;;;;;;;;;;;;;;;;;;;;,;:d0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMKdccccccccccccccccccccccccc:;;;;,,;;,,;;;;;;;;;;;;;;;;;;;;;;;;;,,;;:d0WMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMKdccccccccccccccccccccccc:;;,,;;;,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,;;:d0WMMMMMMMMMMMMMMMMMMMMMMMMM
MMKdccccccccccccccccccccc:;;;;,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,;;;;;;;:d0WMMMMMMMMMMMMMMMMMMMMMMM
MMKdccccccccccccccccccc:;;,;;,,;;,;;;;;;;,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:d0WMMMMMMMMMMMMMMMMMMMMM
MMKdccccccccccccccccc:;;;;;,;;,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,,;;:d0WMMMMMMMMMMMMMMMMMMM
MWKdccccccccccccccc:;;;;;;;,,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,;;,;,,;;:d0WMMMMMMMMMMMMMMMMM
MMKdccccccccccccc:;;,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:d0WMMMMMMMMMMMMMMM
MMKdccccccccccc:;;,;;,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,;;:d0WMMMMMMMMMMMMM
MMKdccccccccc:;;,;;;;;;;;;;;;,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,,;;:d0WMMMMMMMMMMM
MMKdccccccc:;;;;;;;,;;;,;;;,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,,;;:d0WMMMMMMMMM
MWKdccccc:;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:dKWMMMMMMM
MWKdccc:;;,;;,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,,;:d0WMMMMM
MWKdc:;;,;;,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,,;;:d0WMMM
MMXkoooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooood0WMM
MMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM"""